#include "DearImGuiBinding.h"

#include "ImGuiWrapper.h"
#include "ImGuiWrapperSpec.h"
#include "ImGuiInternalWrapper.h"
#include "ImGuiInternalWrapperSpec.h"
#include "ImGuiNotify.hpp"
#include "Engine/Texture.h"
using Wrapper::DockID;

struct DearImGui {};
UsingUClass(UTexture);
UsingNamedCppType(DearImGui, ImGui);
UsingCppType(FImGuiTextureHandle);
UsingCppType(ImVec2);
UsingCppType(ImVec4);
UsingCppType(ImGuiTableSortSpecs);
UsingCppType(ImGuiTableColumnSortSpecs);
UsingCppType(ImNewWrapper);
UsingCppType(ImGuiStyle);
UsingCppType(ImGuiKeyData);
UsingCppType(ImGuiInputTextCallbackData);
UsingCppType(ImGuiSizeCallbackData);
UsingCppType(ImGuiWindowClass);
UsingCppType(ImGuiPayload);
UsingCppType(ImGuiOnceUponAFrame);
UsingCppType(ImGuiListClipper);
UsingCppType(ImDrawVert);
UsingCppType(ImFontAtlasCustomRect);
UsingCppType(ImGuiViewport);
UsingCppType(ImGuiPlatformImeData);
UsingCppType(DockID);
UsingCppType(ImColor);
UsingCppType(ImDrawChannel);
UsingCppType(ImDrawCmd);
UsingCppType(ImDrawCmdHeader);
UsingCppType(ImDrawData);
UsingCppType(ImDrawList);
UsingCppType(ImDrawListSplitter);
UsingCppType(ImFont);
UsingCppType(ImFontAtlas);
UsingCppType(ImFontConfig);
UsingCppType(ImFontGlyph);
UsingCppType(ImFontGlyphRangesBuilder);
UsingCppType(ImGuiContext);
UsingCppType(ImGuiIO);
UsingCppType(ImGuiPlatformIO);
UsingCppType(ImGuiPlatformMonitor);
UsingCppType(ImGuiStorage);
UsingCppType(ImGuiTextBuffer);
UsingCppType(ImGuiTextFilter);

namespace Wrapper{
static void Text(char const* fmt) { ImGui::Text(fmt); }
static void TextColored(ImVec4 const& col, char const* fmt) { ImGui::TextColored(col, fmt); }
static void TextDisabled(char const* fmt) { ImGui::TextDisabled(fmt); }
static void TextWrapped(char const* fmt) { ImGui::TextWrapped(fmt); }
static void LabelText(char const* label, char const* fmt) { ImGui::LabelText(label, fmt); }
static void BulletText(char const* fmt) { ImGui::BulletText(fmt); }
static bool TreeNode(char const* str_id, char const* fmt) { return ImGui::TreeNode(str_id, fmt); }
static bool TreeNode(void const* ptr_id, char const* fmt) { return ImGui::TreeNode(ptr_id, fmt); }
static bool TreeNodeEx(char const* str_id, ImGuiTreeNodeFlags flags, char const* fmt) { return ImGui::TreeNodeEx(str_id, flags, fmt); }
static bool TreeNodeEx(void const* ptr_id, ImGuiTreeNodeFlags flags, char const* fmt) { return ImGui::TreeNodeEx(ptr_id, flags, fmt); }
static void SetTooltip(char const* fmt) { ImGui::SetTooltip(fmt); }
static void SetItemTooltip(char const* fmt) { ImGui::SetItemTooltip(fmt); }
static void LogText(char const* fmt) { ImGui::LogText(fmt); }
}

struct AutoRegisterForDearImGui {
  AutoRegisterForDearImGui() {
    puerts::DefineClass<FImGuiTextureHandle>().Register();
    puerts::DefineClass<ImGuiIO>()
        .Property("ConfigFlags", MakeProperty(&ImGuiIO::ConfigFlags))
        .Property("BackendFlags", MakeProperty(&ImGuiIO::BackendFlags))
        .Property("DisplaySize", MakeProperty(&ImGuiIO::DisplaySize))
        .Property("DeltaTime", MakeProperty(&ImGuiIO::DeltaTime))
        .Property("IniSavingRate", MakeProperty(&ImGuiIO::IniSavingRate))
        .Property("IniFilename", MakeReadonlyProperty(&ImGuiIO::IniFilename))
        .Property("LogFilename", MakeReadonlyProperty(&ImGuiIO::LogFilename))
        .Property("MouseDoubleClickTime",
                  MakeProperty(&ImGuiIO::MouseDoubleClickTime))
        .Property("MouseDoubleClickMaxDist",
                  MakeProperty(&ImGuiIO::MouseDoubleClickMaxDist))
        .Property("MouseDragThreshold",
                  MakeProperty(&ImGuiIO::MouseDragThreshold))
        .Property("KeyMap", MakeProperty(&ImGuiIO::KeyMap))
        .Property("KeyRepeatDelay", MakeProperty(&ImGuiIO::KeyRepeatDelay))
        .Property("KeyRepeatRate", MakeProperty(&ImGuiIO::KeyRepeatRate))
        .Property("UserData", MakeProperty(&ImGuiIO::UserData))
        .Property("Fonts", MakeProperty(&ImGuiIO::Fonts))
        .Property("FontGlobalScale", MakeProperty(&ImGuiIO::FontGlobalScale))
        .Property("FontAllowUserScaling",
                  MakeProperty(&ImGuiIO::FontAllowUserScaling))
        .Property("FontDefault", MakeProperty(&ImGuiIO::FontDefault))
        .Property("DisplayFramebufferScale",
                  MakeProperty(&ImGuiIO::DisplayFramebufferScale))
        .Property("MouseDrawCursor", MakeProperty(&ImGuiIO::MouseDrawCursor))
        .Property("ConfigMacOSXBehaviors",
                  MakeProperty(&ImGuiIO::ConfigMacOSXBehaviors))
        .Property("ConfigInputTextCursorBlink",
                  MakeProperty(&ImGuiIO::ConfigInputTextCursorBlink))
        .Property("ConfigWindowsResizeFromEdges",
                  MakeProperty(&ImGuiIO::ConfigWindowsResizeFromEdges))
        .Property("ConfigWindowsMoveFromTitleBarOnly",
                  MakeProperty(&ImGuiIO::ConfigWindowsMoveFromTitleBarOnly))
        .Property("ConfigMemoryCompactTimer",
                  MakeProperty(&ImGuiIO::ConfigMemoryCompactTimer))
        .Property("BackendPlatformName",
                  MakeReadonlyProperty(&ImGuiIO::BackendPlatformName))
        .Property("BackendRendererName",
                  MakeReadonlyProperty(&ImGuiIO::BackendRendererName))
        .Property("BackendPlatformUserData",
                  MakeProperty(&ImGuiIO::BackendPlatformUserData))
        .Property("BackendRendererUserData",
                  MakeProperty(&ImGuiIO::BackendRendererUserData))
        .Property("BackendLanguageUserData",
                  MakeProperty(&ImGuiIO::BackendLanguageUserData))
        .Property("ClipboardUserData",
                  MakeProperty(&ImGuiIO::ClipboardUserData))
        // .Property("ImeWindowHandle", MakeProperty(&ImGuiIO::ImeWindowHandle))
        .Property("MousePos", MakeProperty(&ImGuiIO::MousePos))
        .Property("MouseDown", MakeProperty(&ImGuiIO::MouseDown))
        .Property("MouseWheel", MakeProperty(&ImGuiIO::MouseWheel))
        .Property("MouseWheelH", MakeProperty(&ImGuiIO::MouseWheelH))
        .Property("KeyCtrl", MakeProperty(&ImGuiIO::KeyCtrl))
        .Property("KeyShift", MakeProperty(&ImGuiIO::KeyShift))
        .Property("KeyAlt", MakeProperty(&ImGuiIO::KeyAlt))
        .Property("KeySuper", MakeProperty(&ImGuiIO::KeySuper))
        .Property("KeysDown", MakeProperty(&ImGuiIO::KeysDown))
        .Property("NavInputs", MakeProperty(&ImGuiIO::NavInputs))
        .Property("WantCaptureMouse", MakeProperty(&ImGuiIO::WantCaptureMouse))
        .Property("WantCaptureKeyboard",
                  MakeProperty(&ImGuiIO::WantCaptureKeyboard))
        .Property("WantTextInput", MakeProperty(&ImGuiIO::WantTextInput))
        .Property("WantSetMousePos", MakeProperty(&ImGuiIO::WantSetMousePos))
        .Property("WantSaveIniSettings",
                  MakeProperty(&ImGuiIO::WantSaveIniSettings))
        .Property("NavActive", MakeProperty(&ImGuiIO::NavActive))
        .Property("NavVisible", MakeProperty(&ImGuiIO::NavVisible))
        .Property("Framerate", MakeProperty(&ImGuiIO::Framerate))
        .Property("MetricsRenderVertices",
                  MakeProperty(&ImGuiIO::MetricsRenderVertices))
        .Property("MetricsRenderIndices",
                  MakeProperty(&ImGuiIO::MetricsRenderIndices))
        .Property("MetricsRenderWindows",
                  MakeProperty(&ImGuiIO::MetricsRenderWindows))
        .Property("MetricsActiveWindows",
                  MakeProperty(&ImGuiIO::MetricsActiveWindows))
        // .Property("MetricsActiveAllocations",
        // MakeProperty(&ImGuiIO::MetricsActiveAllocations))
        .Property("MouseDelta", MakeProperty(&ImGuiIO::MouseDelta))
        .Property("MousePosPrev", MakeProperty(&ImGuiIO::MousePosPrev))
        //.Property("MouseClickedPos", MakeProperty(&ImGuiIO::MouseClickedPos))
        ////ImVec2 MouseClickedPos[5];
        .Property("MouseClickedTime", MakeProperty(&ImGuiIO::MouseClickedTime))
        .Property("MouseClicked", MakeProperty(&ImGuiIO::MouseClicked))
        .Property("MouseDoubleClicked",
                  MakeProperty(&ImGuiIO::MouseDoubleClicked))
        .Property("MouseReleased", MakeProperty(&ImGuiIO::MouseReleased))
        .Property("MouseDownOwned", MakeProperty(&ImGuiIO::MouseDownOwned))
        // .Property("MouseDownWasDoubleClick",
        // MakeProperty(&ImGuiIO::MouseDownWasDoubleClick))
        .Property("MouseDownDuration",
                  MakeProperty(&ImGuiIO::MouseDownDuration))
        .Property("MouseDownDurationPrev",
                  MakeProperty(&ImGuiIO::MouseDownDurationPrev))
        //.Property("MouseDragMaxDistanceAbs",
        // MakeProperty(&ImGuiIO::MouseDragMaxDistanceAbs)) //ImVec2
        // MouseDragMaxDistanceAbs[5]
        .Property("MouseDragMaxDistanceSqr",
                  MakeProperty(&ImGuiIO::MouseDragMaxDistanceSqr))
        // .Property("KeysDownDuration",
        // MakeProperty(&ImGuiIO::KeysDownDuration))
        // .Property("KeysDownDurationPrev",
        // MakeProperty(&ImGuiIO::KeysDownDurationPrev))
        // .Property("NavInputsDownDuration",
        // MakeProperty(&ImGuiIO::NavInputsDownDuration))
        // .Property("NavInputsDownDurationPrev",
        // MakeProperty(&ImGuiIO::NavInputsDownDurationPrev))
        //.Property("InputQueueCharacters",
        // MakeProperty(&ImGuiIO::InputQueueCharacters)) // ImVector
        .Register();
  // AST for 'D:\Dev\OtherGit\webgui/extern/imgui/imgui.h':
    puerts::DefineClass<ImVec2>()
      .Property("x", MakeProperty(&ImVec2::x))
      .Property("y", MakeProperty(&ImVec2::y))
      .Constructor<>()
      .Constructor<float, float>()
      .Register(); // end of ImVec2
    puerts::DefineClass<ImVec4>()
      .Property("x", MakeProperty(&ImVec4::x))
      .Property("y", MakeProperty(&ImVec4::y))
      .Property("z", MakeProperty(&ImVec4::z))
      .Property("w", MakeProperty(&ImVec4::w))
      .Constructor<>()
      .Constructor<float, float, float, float>()
      .Register(); // end of ImVec4
    puerts::DefineClass<ImGuiTableSortSpecs>()
      .Property("Specs", MakeProperty(&ImGuiTableSortSpecs::Specs))
      .Property("SpecsCount", MakeProperty(&ImGuiTableSortSpecs::SpecsCount))
      .Property("SpecsDirty", MakeProperty(&ImGuiTableSortSpecs::SpecsDirty))
      .Constructor<>()
      .Register(); // end of ImGuiTableSortSpecs
    puerts::DefineClass<ImGuiTableColumnSortSpecs>()
      .Property("ColumnUserID", MakeProperty(&ImGuiTableColumnSortSpecs::ColumnUserID))
      .Property("ColumnIndex", MakeProperty(&ImGuiTableColumnSortSpecs::ColumnIndex))
      .Property("SortOrder", MakeProperty(&ImGuiTableColumnSortSpecs::SortOrder))
      .Constructor<>()
      .Register(); // end of ImGuiTableColumnSortSpecs
    puerts::DefineClass<ImNewWrapper>()
    .Register(); // end of ImNewWrapper
    puerts::DefineClass<ImGuiStyle>()
      .Property("Alpha", MakeProperty(&ImGuiStyle::Alpha))
      .Property("DisabledAlpha", MakeProperty(&ImGuiStyle::DisabledAlpha))
      .Property("WindowPadding", MakeProperty(&ImGuiStyle::WindowPadding))
      .Property("WindowRounding", MakeProperty(&ImGuiStyle::WindowRounding))
      .Property("WindowBorderSize", MakeProperty(&ImGuiStyle::WindowBorderSize))
      .Property("WindowMinSize", MakeProperty(&ImGuiStyle::WindowMinSize))
      .Property("WindowTitleAlign", MakeProperty(&ImGuiStyle::WindowTitleAlign))
      .Property("WindowMenuButtonPosition", MakeProperty(&ImGuiStyle::WindowMenuButtonPosition))
      .Property("ChildRounding", MakeProperty(&ImGuiStyle::ChildRounding))
      .Property("ChildBorderSize", MakeProperty(&ImGuiStyle::ChildBorderSize))
      .Property("PopupRounding", MakeProperty(&ImGuiStyle::PopupRounding))
      .Property("PopupBorderSize", MakeProperty(&ImGuiStyle::PopupBorderSize))
      .Property("FramePadding", MakeProperty(&ImGuiStyle::FramePadding))
      .Property("FrameRounding", MakeProperty(&ImGuiStyle::FrameRounding))
      .Property("FrameBorderSize", MakeProperty(&ImGuiStyle::FrameBorderSize))
      .Property("ItemSpacing", MakeProperty(&ImGuiStyle::ItemSpacing))
      .Property("ItemInnerSpacing", MakeProperty(&ImGuiStyle::ItemInnerSpacing))
      .Property("CellPadding", MakeProperty(&ImGuiStyle::CellPadding))
      .Property("TouchExtraPadding", MakeProperty(&ImGuiStyle::TouchExtraPadding))
      .Property("IndentSpacing", MakeProperty(&ImGuiStyle::IndentSpacing))
      .Property("ColumnsMinSpacing", MakeProperty(&ImGuiStyle::ColumnsMinSpacing))
      .Property("ScrollbarSize", MakeProperty(&ImGuiStyle::ScrollbarSize))
      .Property("ScrollbarRounding", MakeProperty(&ImGuiStyle::ScrollbarRounding))
      .Property("GrabMinSize", MakeProperty(&ImGuiStyle::GrabMinSize))
      .Property("GrabRounding", MakeProperty(&ImGuiStyle::GrabRounding))
      .Property("LogSliderDeadzone", MakeProperty(&ImGuiStyle::LogSliderDeadzone))
      .Property("TabRounding", MakeProperty(&ImGuiStyle::TabRounding))
      .Property("TabBorderSize", MakeProperty(&ImGuiStyle::TabBorderSize))
      .Property("TabMinWidthForCloseButton", MakeProperty(&ImGuiStyle::TabMinWidthForCloseButton))
      .Property("TabBarBorderSize", MakeProperty(&ImGuiStyle::TabBarBorderSize))
      .Property("TableAngledHeadersAngle", MakeProperty(&ImGuiStyle::TableAngledHeadersAngle))
      .Property("ColorButtonPosition", MakeProperty(&ImGuiStyle::ColorButtonPosition))
      .Property("ButtonTextAlign", MakeProperty(&ImGuiStyle::ButtonTextAlign))
      .Property("SelectableTextAlign", MakeProperty(&ImGuiStyle::SelectableTextAlign))
      .Property("SeparatorTextBorderSize", MakeProperty(&ImGuiStyle::SeparatorTextBorderSize))
      .Property("SeparatorTextAlign", MakeProperty(&ImGuiStyle::SeparatorTextAlign))
      .Property("SeparatorTextPadding", MakeProperty(&ImGuiStyle::SeparatorTextPadding))
      .Property("DisplayWindowPadding", MakeProperty(&ImGuiStyle::DisplayWindowPadding))
      .Property("DisplaySafeAreaPadding", MakeProperty(&ImGuiStyle::DisplaySafeAreaPadding))
      .Property("DockingSeparatorSize", MakeProperty(&ImGuiStyle::DockingSeparatorSize))
      .Property("MouseCursorScale", MakeProperty(&ImGuiStyle::MouseCursorScale))
      .Property("AntiAliasedLines", MakeProperty(&ImGuiStyle::AntiAliasedLines))
      .Property("AntiAliasedLinesUseTex", MakeProperty(&ImGuiStyle::AntiAliasedLinesUseTex))
      .Property("AntiAliasedFill", MakeProperty(&ImGuiStyle::AntiAliasedFill))
      .Property("CurveTessellationTol", MakeProperty(&ImGuiStyle::CurveTessellationTol))
      .Property("CircleTessellationMaxError", MakeProperty(&ImGuiStyle::CircleTessellationMaxError))
      .Property("HoverStationaryDelay", MakeProperty(&ImGuiStyle::HoverStationaryDelay))
      .Property("HoverDelayShort", MakeProperty(&ImGuiStyle::HoverDelayShort))
      .Property("HoverDelayNormal", MakeProperty(&ImGuiStyle::HoverDelayNormal))
      .Property("HoverFlagsForTooltipMouse", MakeProperty(&ImGuiStyle::HoverFlagsForTooltipMouse))
      .Property("HoverFlagsForTooltipNav", MakeProperty(&ImGuiStyle::HoverFlagsForTooltipNav))
      .Constructor<>()
      .Method("ScaleAllSizes", MakeFunction(&ImGuiStyle::ScaleAllSizes))
      .Register(); // end of ImGuiStyle
    puerts::DefineClass<ImGuiKeyData>()
      .Property("Down", MakeProperty(&ImGuiKeyData::Down))
      .Property("DownDuration", MakeProperty(&ImGuiKeyData::DownDuration))
      .Property("DownDurationPrev", MakeProperty(&ImGuiKeyData::DownDurationPrev))
      .Property("AnalogValue", MakeProperty(&ImGuiKeyData::AnalogValue))
      .Register(); // end of ImGuiKeyData
    puerts::DefineClass<ImGuiInputTextCallbackData>()
      .Property("Ctx", MakeProperty(&ImGuiInputTextCallbackData::Ctx))
      .Property("EventFlag", MakeProperty(&ImGuiInputTextCallbackData::EventFlag))
      .Property("Flags", MakeProperty(&ImGuiInputTextCallbackData::Flags))
      .Property("UserData", MakeProperty(&ImGuiInputTextCallbackData::UserData))
      .Property("EventChar", MakeProperty(&ImGuiInputTextCallbackData::EventChar))
      .Property("EventKey", MakeProperty(&ImGuiInputTextCallbackData::EventKey))
      .Property("BufTextLen", MakeProperty(&ImGuiInputTextCallbackData::BufTextLen))
      .Property("BufSize", MakeProperty(&ImGuiInputTextCallbackData::BufSize))
      .Property("BufDirty", MakeProperty(&ImGuiInputTextCallbackData::BufDirty))
      .Property("CursorPos", MakeProperty(&ImGuiInputTextCallbackData::CursorPos))
      .Property("SelectionStart", MakeProperty(&ImGuiInputTextCallbackData::SelectionStart))
      .Property("SelectionEnd", MakeProperty(&ImGuiInputTextCallbackData::SelectionEnd))
      .Constructor<>()
      .Method("DeleteChars", MakeFunction(&ImGuiInputTextCallbackData::DeleteChars))
      .Method("InsertChars", MakeFunction(&ImGuiInputTextCallbackData::InsertChars))
      .Method("SelectAll", MakeFunction(&ImGuiInputTextCallbackData::SelectAll))
      .Method("ClearSelection", MakeFunction(&ImGuiInputTextCallbackData::ClearSelection))
      .Method("HasSelection", MakeFunction(&ImGuiInputTextCallbackData::HasSelection))
      .Register(); // end of ImGuiInputTextCallbackData
    puerts::DefineClass<ImGuiSizeCallbackData>()
      .Property("UserData", MakeProperty(&ImGuiSizeCallbackData::UserData))
      .Property("Pos", MakeProperty(&ImGuiSizeCallbackData::Pos))
      .Property("CurrentSize", MakeProperty(&ImGuiSizeCallbackData::CurrentSize))
      .Property("DesiredSize", MakeProperty(&ImGuiSizeCallbackData::DesiredSize))
      .Register(); // end of ImGuiSizeCallbackData
    puerts::DefineClass<ImGuiWindowClass>()
      .Property("ClassId", MakeProperty(&ImGuiWindowClass::ClassId))
      .Property("ParentViewportId", MakeProperty(&ImGuiWindowClass::ParentViewportId))
      .Property("FocusRouteParentWindowId", MakeProperty(&ImGuiWindowClass::FocusRouteParentWindowId))
      .Property("ViewportFlagsOverrideSet", MakeProperty(&ImGuiWindowClass::ViewportFlagsOverrideSet))
      .Property("ViewportFlagsOverrideClear", MakeProperty(&ImGuiWindowClass::ViewportFlagsOverrideClear))
      .Property("TabItemFlagsOverrideSet", MakeProperty(&ImGuiWindowClass::TabItemFlagsOverrideSet))
      .Property("DockNodeFlagsOverrideSet", MakeProperty(&ImGuiWindowClass::DockNodeFlagsOverrideSet))
      .Property("DockingAlwaysTabBar", MakeProperty(&ImGuiWindowClass::DockingAlwaysTabBar))
      .Property("DockingAllowUnclassed", MakeProperty(&ImGuiWindowClass::DockingAllowUnclassed))
      .Constructor<>()
      .Register(); // end of ImGuiWindowClass
    puerts::DefineClass<ImGuiPayload>()
      .Property("Data", MakeProperty(&ImGuiPayload::Data))
      .Property("DataSize", MakeProperty(&ImGuiPayload::DataSize))
      .Property("SourceId", MakeProperty(&ImGuiPayload::SourceId))
      .Property("SourceParentId", MakeProperty(&ImGuiPayload::SourceParentId))
      .Property("DataFrameCount", MakeProperty(&ImGuiPayload::DataFrameCount))
      .Property("Preview", MakeProperty(&ImGuiPayload::Preview))
      .Property("Delivery", MakeProperty(&ImGuiPayload::Delivery))
      .Constructor<>()
      .Method("Clear", MakeFunction(&ImGuiPayload::Clear))
      .Method("IsDataType", MakeFunction(&ImGuiPayload::IsDataType))
      .Method("IsPreview", MakeFunction(&ImGuiPayload::IsPreview))
      .Method("IsDelivery", MakeFunction(&ImGuiPayload::IsDelivery))
      .Register(); // end of ImGuiPayload
    puerts::DefineClass<ImGuiOnceUponAFrame>()
      .Constructor<>()
      .Property("RefFrame", MakeProperty(&ImGuiOnceUponAFrame::RefFrame))
      .Register(); // end of ImGuiOnceUponAFrame
    puerts::DefineClass<ImGuiListClipper>()
      .Property("Ctx", MakeProperty(&ImGuiListClipper::Ctx))
      .Property("DisplayStart", MakeProperty(&ImGuiListClipper::DisplayStart))
      .Property("DisplayEnd", MakeProperty(&ImGuiListClipper::DisplayEnd))
      .Property("ItemsCount", MakeProperty(&ImGuiListClipper::ItemsCount))
      .Property("ItemsHeight", MakeProperty(&ImGuiListClipper::ItemsHeight))
      .Property("StartPosY", MakeProperty(&ImGuiListClipper::StartPosY))
      .Property("TempData", MakeProperty(&ImGuiListClipper::TempData))
      .Constructor<>()
      .Method("Begin", MakeFunction(&ImGuiListClipper::Begin))
      .Method("End", MakeFunction(&ImGuiListClipper::End))
      .Method("Step", MakeFunction(&ImGuiListClipper::Step))
      .Method("IncludeItemByIndex", MakeFunction(&ImGuiListClipper::IncludeItemByIndex))
      .Method("IncludeItemsByIndex", MakeFunction(&ImGuiListClipper::IncludeItemsByIndex))
      .Register(); // end of ImGuiListClipper
    puerts::DefineClass<ImDrawVert>()
      .Property("pos", MakeProperty(&ImDrawVert::pos))
      .Property("uv", MakeProperty(&ImDrawVert::uv))
      .Property("col", MakeProperty(&ImDrawVert::col))
      .Register(); // end of ImDrawVert
    puerts::DefineClass<ImFontAtlasCustomRect>()
      .Property("Width", MakeProperty(&ImFontAtlasCustomRect::Width))
      .Property("Height", MakeProperty(&ImFontAtlasCustomRect::Height))
      .Property("X", MakeProperty(&ImFontAtlasCustomRect::X))
      .Property("Y", MakeProperty(&ImFontAtlasCustomRect::Y))
      .Property("GlyphID", MakeProperty(&ImFontAtlasCustomRect::GlyphID))
      .Property("GlyphAdvanceX", MakeProperty(&ImFontAtlasCustomRect::GlyphAdvanceX))
      .Property("GlyphOffset", MakeProperty(&ImFontAtlasCustomRect::GlyphOffset))
      .Property("Font", MakeProperty(&ImFontAtlasCustomRect::Font))
      .Constructor<>()
      .Method("IsPacked", MakeFunction(&ImFontAtlasCustomRect::IsPacked))
      .Register(); // end of ImFontAtlasCustomRect
    puerts::DefineClass<ImGuiViewport>()
      .Property("ID", MakeProperty(&ImGuiViewport::ID))
      .Property("Flags", MakeProperty(&ImGuiViewport::Flags))
      .Property("Pos", MakeProperty(&ImGuiViewport::Pos))
      .Property("Size", MakeProperty(&ImGuiViewport::Size))
      .Property("WorkPos", MakeProperty(&ImGuiViewport::WorkPos))
      .Property("WorkSize", MakeProperty(&ImGuiViewport::WorkSize))
      .Property("DpiScale", MakeProperty(&ImGuiViewport::DpiScale))
      .Property("ParentViewportId", MakeProperty(&ImGuiViewport::ParentViewportId))
      .Property("DrawData", MakeProperty(&ImGuiViewport::DrawData))
      .Property("RendererUserData", MakeProperty(&ImGuiViewport::RendererUserData))
      .Property("PlatformUserData", MakeProperty(&ImGuiViewport::PlatformUserData))
      .Property("PlatformHandle", MakeProperty(&ImGuiViewport::PlatformHandle))
      .Property("PlatformHandleRaw", MakeProperty(&ImGuiViewport::PlatformHandleRaw))
      .Property("PlatformWindowCreated", MakeProperty(&ImGuiViewport::PlatformWindowCreated))
      .Property("PlatformRequestMove", MakeProperty(&ImGuiViewport::PlatformRequestMove))
      .Property("PlatformRequestResize", MakeProperty(&ImGuiViewport::PlatformRequestResize))
      .Property("PlatformRequestClose", MakeProperty(&ImGuiViewport::PlatformRequestClose))
      .Constructor<>()
      .Method("GetCenter", MakeFunction(&ImGuiViewport::GetCenter))
      .Method("GetWorkCenter", MakeFunction(&ImGuiViewport::GetWorkCenter))
      .Register(); // end of ImGuiViewport
    puerts::DefineClass<ImGuiPlatformImeData>()
      .Property("WantVisible", MakeProperty(&ImGuiPlatformImeData::WantVisible))
      .Property("InputPos", MakeProperty(&ImGuiPlatformImeData::InputPos))
      .Property("InputLineHeight", MakeProperty(&ImGuiPlatformImeData::InputLineHeight))
      .Constructor<>()
      .Register(); // end of ImGuiPlatformImeData
  // AST for 'D:\Dev\OtherGit\webgui/extern/ImGuiWrapper.h':
  // AST for 'D:\Dev\OtherGit\webgui/extern/ImGuiInternalWrapper.h':
    puerts::DefineClass<DockID>()
      .Property("id_at_dir", MakeProperty(&DockID::id_at_dir))
      .Property("id_at_opposite_dir", MakeProperty(&DockID::id_at_opposite_dir))
      .Constructor<>()
      .Register(); // end of DockID
    puerts::DefineClass<DearImGui>()
      .Function("CreateContext", MakeFunction(&ImGui::CreateContext))
      .Function("DestroyContext", MakeFunction(&ImGui::DestroyContext))
      .Function("GetCurrentContext", MakeFunction(&ImGui::GetCurrentContext))
      .Function("SetCurrentContext", MakeFunction(&ImGui::SetCurrentContext))
      .Function("GetIO", MakeFunction(&ImGui::GetIO))
      .Function("GetStyle", MakeFunction(&ImGui::GetStyle))
      .Function("NewFrame", MakeFunction(&ImGui::NewFrame))
      .Function("EndFrame", MakeFunction(&ImGui::EndFrame))
      .Function("Render", MakeFunction(&ImGui::Render))
      .Function("GetDrawData", MakeFunction(&ImGui::GetDrawData))
      .Function("ShowDemoWindow", MakeFunction(&ImGui::ShowDemoWindow))
      .Function("ShowMetricsWindow", MakeFunction(&ImGui::ShowMetricsWindow))
      .Function("ShowDebugLogWindow", MakeFunction(&ImGui::ShowDebugLogWindow))
      .Function("ShowIDStackToolWindow", MakeFunction(&ImGui::ShowIDStackToolWindow))
      .Function("ShowAboutWindow", MakeFunction(&ImGui::ShowAboutWindow))
      .Function("ShowStyleEditor", MakeFunction(&ImGui::ShowStyleEditor))
      .Function("ShowStyleSelector", MakeFunction(&ImGui::ShowStyleSelector))
      .Function("ShowFontSelector", MakeFunction(&ImGui::ShowFontSelector))
      .Function("ShowUserGuide", MakeFunction(&ImGui::ShowUserGuide))
      .Function("GetVersion", MakeFunction(&ImGui::GetVersion))
      .Function("StyleColorsDark", MakeFunction(&ImGui::StyleColorsDark))
      .Function("StyleColorsLight", MakeFunction(&ImGui::StyleColorsLight))
      .Function("StyleColorsClassic", MakeFunction(&ImGui::StyleColorsClassic))
      .Function("Begin", MakeFunction(&ImGui::Begin))
      .Function("End", MakeFunction(&ImGui::End))
      .Function("BeginChild", SelectFunction(bool(*)(char const*, ImVec2 const&, ImGuiChildFlags, ImGuiWindowFlags), &ImGui::BeginChild))
      .Function("BeginChild_1", SelectFunction(bool(*)(ImGuiID, ImVec2 const&, ImGuiChildFlags, ImGuiWindowFlags), &ImGui::BeginChild))
      .Function("EndChild", MakeFunction(&ImGui::EndChild))
      .Function("IsWindowAppearing", MakeFunction(&ImGui::IsWindowAppearing))
      .Function("IsWindowCollapsed", MakeFunction(&ImGui::IsWindowCollapsed))
      .Function("IsWindowFocused", MakeFunction(&ImGui::IsWindowFocused))
      .Function("IsWindowHovered", MakeFunction(&ImGui::IsWindowHovered))
      .Function("GetWindowDrawList", MakeFunction(&ImGui::GetWindowDrawList))
      .Function("GetWindowDpiScale", MakeFunction(&ImGui::GetWindowDpiScale))
      .Function("GetWindowPos", MakeFunction(&ImGui::GetWindowPos))
      .Function("GetWindowSize", MakeFunction(&ImGui::GetWindowSize))
      .Function("GetWindowWidth", MakeFunction(&ImGui::GetWindowWidth))
      .Function("GetWindowHeight", MakeFunction(&ImGui::GetWindowHeight))
      .Function("GetWindowViewport", MakeFunction(&ImGui::GetWindowViewport))
      .Function("SetNextWindowPos", MakeFunction(&ImGui::SetNextWindowPos))
      .Function("SetNextWindowSize", MakeFunction(&ImGui::SetNextWindowSize))
      .Function("SetNextWindowContentSize", MakeFunction(&ImGui::SetNextWindowContentSize))
      .Function("SetNextWindowCollapsed", MakeFunction(&ImGui::SetNextWindowCollapsed))
      .Function("SetNextWindowFocus", MakeFunction(&ImGui::SetNextWindowFocus))
      .Function("SetNextWindowScroll", MakeFunction(&ImGui::SetNextWindowScroll))
      .Function("SetNextWindowBgAlpha", MakeFunction(&ImGui::SetNextWindowBgAlpha))
      .Function("SetNextWindowViewport", MakeFunction(&ImGui::SetNextWindowViewport))
      .Function("SetWindowPos", SelectFunction(void(*)(ImVec2 const&, ImGuiCond), &ImGui::SetWindowPos))
      .Function("SetWindowSize", SelectFunction(void(*)(ImVec2 const&, ImGuiCond), &ImGui::SetWindowSize))
      .Function("SetWindowCollapsed", SelectFunction(void(*)(bool, ImGuiCond), &ImGui::SetWindowCollapsed))
      .Function("SetWindowFocus", SelectFunction(void(*)(), &ImGui::SetWindowFocus))
      .Function("SetWindowFontScale", MakeFunction(&ImGui::SetWindowFontScale))
      .Function("SetWindowPos_1", SelectFunction(void(*)(char const*, ImVec2 const&, ImGuiCond), &ImGui::SetWindowPos))
      .Function("SetWindowSize_1", SelectFunction(void(*)(char const*, ImVec2 const&, ImGuiCond), &ImGui::SetWindowSize))
      .Function("SetWindowCollapsed_1", SelectFunction(void(*)(char const*, bool, ImGuiCond), &ImGui::SetWindowCollapsed))
      .Function("SetWindowFocus_1", SelectFunction(void(*)(char const*), &ImGui::SetWindowFocus))
      .Function("GetContentRegionAvail", MakeFunction(&ImGui::GetContentRegionAvail))
      .Function("GetContentRegionMax", MakeFunction(&ImGui::GetContentRegionMax))
      .Function("GetWindowContentRegionMin", MakeFunction(&ImGui::GetWindowContentRegionMin))
      .Function("GetWindowContentRegionMax", MakeFunction(&ImGui::GetWindowContentRegionMax))
      .Function("GetScrollX", MakeFunction(&ImGui::GetScrollX))
      .Function("GetScrollY", MakeFunction(&ImGui::GetScrollY))
      .Function("GetScrollMaxX", MakeFunction(&ImGui::GetScrollMaxX))
      .Function("GetScrollMaxY", MakeFunction(&ImGui::GetScrollMaxY))
      .Function("SetScrollHereX", MakeFunction(&ImGui::SetScrollHereX))
      .Function("SetScrollHereY", MakeFunction(&ImGui::SetScrollHereY))
      .Function("PushFont", MakeFunction(&ImGui::PushFont))
      .Function("PopFont", MakeFunction(&ImGui::PopFont))
      .Function("PushStyleColor", SelectFunction(void(*)(ImGuiCol, ImU32), &ImGui::PushStyleColor))
      .Function("PushStyleColor_1", SelectFunction(void(*)(ImGuiCol, ImVec4 const&), &ImGui::PushStyleColor))
      .Function("PopStyleColor", MakeFunction(&ImGui::PopStyleColor))
      .Function("PushStyleVar", SelectFunction(void(*)(ImGuiStyleVar, float), &ImGui::PushStyleVar))
      .Function("PushStyleVar_1", SelectFunction(void(*)(ImGuiStyleVar, ImVec2 const&), &ImGui::PushStyleVar))
      .Function("PopStyleVar", MakeFunction(&ImGui::PopStyleVar))
      .Function("PushTabStop", MakeFunction(&ImGui::PushTabStop))
      .Function("PopTabStop", MakeFunction(&ImGui::PopTabStop))
      .Function("PushButtonRepeat", MakeFunction(&ImGui::PushButtonRepeat))
      .Function("PopButtonRepeat", MakeFunction(&ImGui::PopButtonRepeat))
      .Function("PushItemWidth", MakeFunction(&ImGui::PushItemWidth))
      .Function("PopItemWidth", MakeFunction(&ImGui::PopItemWidth))
      .Function("SetNextItemWidth", MakeFunction(&ImGui::SetNextItemWidth))
      .Function("CalcItemWidth", MakeFunction(&ImGui::CalcItemWidth))
      .Function("PushTextWrapPos", MakeFunction(&ImGui::PushTextWrapPos))
      .Function("PopTextWrapPos", MakeFunction(&ImGui::PopTextWrapPos))
      .Function("GetFont", MakeFunction(&ImGui::GetFont))
      .Function("GetFontSize", MakeFunction(&ImGui::GetFontSize))
      .Function("GetFontTexUvWhitePixel", MakeFunction(&ImGui::GetFontTexUvWhitePixel))
      .Function("GetColorU32", SelectFunction(ImU32(*)(ImGuiCol, float), &ImGui::GetColorU32))
      .Function("GetColorU32_1", SelectFunction(ImU32(*)(ImVec4 const&), &ImGui::GetColorU32))
      .Function("GetColorU32_2", SelectFunction(ImU32(*)(ImU32, float), &ImGui::GetColorU32))
      .Function("GetCursorScreenPos", MakeFunction(&ImGui::GetCursorScreenPos))
      .Function("SetCursorScreenPos", MakeFunction(&ImGui::SetCursorScreenPos))
      .Function("GetCursorPos", MakeFunction(&ImGui::GetCursorPos))
      .Function("GetCursorPosX", MakeFunction(&ImGui::GetCursorPosX))
      .Function("GetCursorPosY", MakeFunction(&ImGui::GetCursorPosY))
      .Function("SetCursorPos", MakeFunction(&ImGui::SetCursorPos))
      .Function("SetCursorPosX", MakeFunction(&ImGui::SetCursorPosX))
      .Function("SetCursorPosY", MakeFunction(&ImGui::SetCursorPosY))
      .Function("GetCursorStartPos", MakeFunction(&ImGui::GetCursorStartPos))
      .Function("Separator", MakeFunction(&ImGui::Separator))
      .Function("SameLine", MakeFunction(&ImGui::SameLine))
      .Function("NewLine", MakeFunction(&ImGui::NewLine))
      .Function("Spacing", MakeFunction(&ImGui::Spacing))
      .Function("Dummy", MakeFunction(&ImGui::Dummy))
      .Function("Indent", MakeFunction(&ImGui::Indent))
      .Function("Unindent", MakeFunction(&ImGui::Unindent))
      .Function("BeginGroup", MakeFunction(&ImGui::BeginGroup))
      .Function("EndGroup", MakeFunction(&ImGui::EndGroup))
      .Function("AlignTextToFramePadding", MakeFunction(&ImGui::AlignTextToFramePadding))
      .Function("GetTextLineHeight", MakeFunction(&ImGui::GetTextLineHeight))
      .Function("GetTextLineHeightWithSpacing", MakeFunction(&ImGui::GetTextLineHeightWithSpacing))
      .Function("GetFrameHeight", MakeFunction(&ImGui::GetFrameHeight))
      .Function("GetFrameHeightWithSpacing", MakeFunction(&ImGui::GetFrameHeightWithSpacing))
      .Function("PushID", SelectFunction(void(*)(char const*), &ImGui::PushID))
      .Function("PushID_1", SelectFunction(void(*)(char const*, char const*), &ImGui::PushID))
      .Function("PushID_2", SelectFunction(void(*)(void const*), &ImGui::PushID))
      .Function("PushID_3", SelectFunction(void(*)(int), &ImGui::PushID))
      .Function("PopID", MakeFunction(&ImGui::PopID))
      .Function("GetID", SelectFunction(ImGuiID(*)(char const*), &ImGui::GetID))
      .Function("GetID_1", SelectFunction(ImGuiID(*)(char const*, char const*), &ImGui::GetID))
      .Function("GetID_2", SelectFunction(ImGuiID(*)(void const*), &ImGui::GetID))
      .Function("TextUnformatted", MakeFunction(&ImGui::TextUnformatted))
      .Function("Text", SelectFunction(void(*)(char const*), &Wrapper::Text))
      .Function("TextColored", SelectFunction(void(*)(ImVec4 const&, char const*), &Wrapper::TextColored))
      .Function("TextDisabled", SelectFunction(void(*)(char const*), &Wrapper::TextDisabled))
      .Function("TextWrapped", SelectFunction(void(*)(char const*), &Wrapper::TextWrapped))
      .Function("LabelText", SelectFunction(void(*)(char const*, char const*), &Wrapper::LabelText))
      .Function("BulletText", SelectFunction(void(*)(char const*), &Wrapper::BulletText))
      .Function("SeparatorText", MakeFunction(&ImGui::SeparatorText))
      .Function("Button", MakeFunction(&ImGui::Button))
      .Function("SmallButton", MakeFunction(&ImGui::SmallButton))
      .Function("InvisibleButton", MakeFunction(&ImGui::InvisibleButton))
      .Function("ArrowButton", MakeFunction(&ImGui::ArrowButton))
      .Function("Checkbox", MakeFunction(&ImGui::Checkbox))
      .Function("CheckboxFlags", SelectFunction(bool(*)(char const*, int*, int), &ImGui::CheckboxFlags))
      .Function("CheckboxFlags_1", SelectFunction(bool(*)(char const*, unsigned int*, unsigned int), &ImGui::CheckboxFlags))
      .Function("RadioButton", SelectFunction(bool(*)(char const*, bool), &ImGui::RadioButton))
      .Function("RadioButton_1", SelectFunction(bool(*)(char const*, int*, int), &ImGui::RadioButton))
      .Function("ProgressBar", MakeFunction(&ImGui::ProgressBar))
      .Function("Bullet", MakeFunction(&ImGui::Bullet))
      .Function("BeginCombo", MakeFunction(&ImGui::BeginCombo))
      .Function("EndCombo", MakeFunction(&ImGui::EndCombo))
      .Function("DragFloat", MakeFunction(&ImGui::DragFloat))
      .Function("DragFloat2", MakeFunctionWithScriptTypePtr(&ImGui::DragFloat2))
      .Function("DragFloat3", MakeFunctionWithScriptTypePtr(&ImGui::DragFloat3))
      .Function("DragFloat4", MakeFunctionWithScriptTypePtr(&ImGui::DragFloat4))
      .Function("DragFloatRange2", MakeFunction(&ImGui::DragFloatRange2))
      .Function("DragInt", MakeFunction(&ImGui::DragInt))
      .Function("DragInt2", MakeFunctionWithScriptTypePtr(&ImGui::DragInt2))
      .Function("DragInt3", MakeFunctionWithScriptTypePtr(&ImGui::DragInt3))
      .Function("DragInt4", MakeFunctionWithScriptTypePtr(&ImGui::DragInt4))
      .Function("DragIntRange2", MakeFunction(&ImGui::DragIntRange2))
      .Function("DragScalar", MakeFunction(&ImGui::DragScalar))
      .Function("DragScalarN", MakeFunction(&ImGui::DragScalarN))
      .Function("SliderFloat", MakeFunction(&ImGui::SliderFloat))
      .Function("SliderFloat2", MakeFunctionWithScriptTypePtr(&ImGui::SliderFloat2))
      .Function("SliderFloat3", MakeFunctionWithScriptTypePtr(&ImGui::SliderFloat3))
      .Function("SliderFloat4", MakeFunctionWithScriptTypePtr(&ImGui::SliderFloat4))
      .Function("SliderAngle", MakeFunction(&ImGui::SliderAngle))
      .Function("SliderInt", MakeFunction(&ImGui::SliderInt))
      .Function("SliderInt2", MakeFunctionWithScriptTypePtr(&ImGui::SliderInt2))
      .Function("SliderInt3", MakeFunctionWithScriptTypePtr(&ImGui::SliderInt3))
      .Function("SliderInt4", MakeFunctionWithScriptTypePtr(&ImGui::SliderInt4))
      .Function("SliderScalar", MakeFunction(&ImGui::SliderScalar))
      .Function("SliderScalarN", MakeFunction(&ImGui::SliderScalarN))
      .Function("VSliderFloat", MakeFunction(&ImGui::VSliderFloat))
      .Function("VSliderInt", MakeFunction(&ImGui::VSliderInt))
      .Function("VSliderScalar", MakeFunction(&ImGui::VSliderScalar))
      .Function("InputFloat", MakeFunction(&ImGui::InputFloat))
      .Function("InputFloat2", MakeFunctionWithScriptTypePtr(&ImGui::InputFloat2))
      .Function("InputFloat3", MakeFunctionWithScriptTypePtr(&ImGui::InputFloat3))
      .Function("InputFloat4", MakeFunctionWithScriptTypePtr(&ImGui::InputFloat4))
      .Function("InputInt", MakeFunction(&ImGui::InputInt))
      .Function("InputInt2", MakeFunctionWithScriptTypePtr(&ImGui::InputInt2))
      .Function("InputInt3", MakeFunctionWithScriptTypePtr(&ImGui::InputInt3))
      .Function("InputInt4", MakeFunctionWithScriptTypePtr(&ImGui::InputInt4))
      .Function("InputDouble", MakeFunction(&ImGui::InputDouble))
      .Function("InputScalar", MakeFunction(&ImGui::InputScalar))
      .Function("InputScalarN", MakeFunction(&ImGui::InputScalarN))
      .Function("ColorEdit3", MakeFunctionWithScriptTypePtr(&ImGui::ColorEdit3))
      .Function("ColorEdit4", MakeFunctionWithScriptTypePtr(&ImGui::ColorEdit4))
      .Function("ColorPicker3", MakeFunctionWithScriptTypePtr(&ImGui::ColorPicker3))
      .Function("ColorPicker4", MakeFunctionWithScriptTypePtr(&ImGui::ColorPicker4))
      .Function("ColorButton", MakeFunction(&ImGui::ColorButton))
      .Function("SetColorEditOptions", MakeFunction(&ImGui::SetColorEditOptions))
      .Function("TreeNode", SelectFunction(bool(*)(char const*), &ImGui::TreeNode))
      .Function("TreeNode_1", SelectFunction(bool(*)(char const*, char const*), &Wrapper::TreeNode))
      .Function("TreeNode_2", SelectFunction(bool(*)(void const*, char const*), &Wrapper::TreeNode))
      .Function("TreeNodeEx", SelectFunction(bool(*)(char const*, ImGuiTreeNodeFlags), &ImGui::TreeNodeEx))
      .Function("TreeNodeEx_1", SelectFunction(bool(*)(char const*, ImGuiTreeNodeFlags, char const*), &Wrapper::TreeNodeEx))
      .Function("TreeNodeEx_2", SelectFunction(bool(*)(void const*, ImGuiTreeNodeFlags, char const*), &Wrapper::TreeNodeEx))
      .Function("TreePush", SelectFunction(void(*)(char const*), &ImGui::TreePush))
      .Function("TreePush_1", SelectFunction(void(*)(void const*), &ImGui::TreePush))
      .Function("TreePop", MakeFunction(&ImGui::TreePop))
      .Function("GetTreeNodeToLabelSpacing", MakeFunction(&ImGui::GetTreeNodeToLabelSpacing))
      .Function("CollapsingHeader", SelectFunction(bool(*)(char const*, ImGuiTreeNodeFlags), &ImGui::CollapsingHeader))
      .Function("CollapsingHeader_1", SelectFunction(bool(*)(char const*, bool*, ImGuiTreeNodeFlags), &ImGui::CollapsingHeader))
      .Function("SetNextItemOpen", MakeFunction(&ImGui::SetNextItemOpen))
      .Function("Selectable", SelectFunction(bool(*)(char const*, bool, ImGuiSelectableFlags, ImVec2 const&), &ImGui::Selectable))
      .Function("Selectable_1", SelectFunction(bool(*)(char const*, bool*, ImGuiSelectableFlags, ImVec2 const&), &ImGui::Selectable))
      .Function("BeginListBox", MakeFunction(&ImGui::BeginListBox))
      .Function("EndListBox", MakeFunction(&ImGui::EndListBox))
      .Function("Value", SelectFunction(void(*)(char const*, bool), &ImGui::Value))
      .Function("Value_1", SelectFunction(void(*)(char const*, int), &ImGui::Value))
      .Function("Value_2", SelectFunction(void(*)(char const*, unsigned int), &ImGui::Value))
      .Function("Value_3", SelectFunction(void(*)(char const*, float, char const*), &ImGui::Value))
      .Function("BeginMenuBar", MakeFunction(&ImGui::BeginMenuBar))
      .Function("EndMenuBar", MakeFunction(&ImGui::EndMenuBar))
      .Function("BeginMainMenuBar", MakeFunction(&ImGui::BeginMainMenuBar))
      .Function("EndMainMenuBar", MakeFunction(&ImGui::EndMainMenuBar))
      .Function("BeginMenu", MakeFunction(&ImGui::BeginMenu))
      .Function("EndMenu", MakeFunction(&ImGui::EndMenu))
      .Function("MenuItem", SelectFunction(bool(*)(char const*, char const*, bool, bool), &ImGui::MenuItem))
      .Function("MenuItem_1", SelectFunction(bool(*)(char const*, char const*, bool*, bool), &ImGui::MenuItem))
      .Function("BeginTooltip", MakeFunction(&ImGui::BeginTooltip))
      .Function("EndTooltip", MakeFunction(&ImGui::EndTooltip))
      .Function("SetTooltip", SelectFunction(void(*)(char const*), &Wrapper::SetTooltip))
      .Function("BeginItemTooltip", MakeFunction(&ImGui::BeginItemTooltip))
      .Function("SetItemTooltip", SelectFunction(void(*)(char const*), &Wrapper::SetItemTooltip))
      .Function("BeginPopup", MakeFunction(&ImGui::BeginPopup))
      .Function("BeginPopupModal", MakeFunction(&ImGui::BeginPopupModal))
      .Function("EndPopup", MakeFunction(&ImGui::EndPopup))
      .Function("OpenPopup", SelectFunction(void(*)(char const*, ImGuiPopupFlags), &ImGui::OpenPopup))
      .Function("OpenPopup_1", SelectFunction(void(*)(ImGuiID, ImGuiPopupFlags), &ImGui::OpenPopup))
      .Function("OpenPopupOnItemClick", MakeFunction(&ImGui::OpenPopupOnItemClick))
      .Function("CloseCurrentPopup", MakeFunction(&ImGui::CloseCurrentPopup))
      .Function("BeginPopupContextItem", MakeFunction(&ImGui::BeginPopupContextItem))
      .Function("BeginPopupContextWindow", MakeFunction(&ImGui::BeginPopupContextWindow))
      .Function("BeginPopupContextVoid", MakeFunction(&ImGui::BeginPopupContextVoid))
      .Function("BeginTable", MakeFunction(&ImGui::BeginTable))
      .Function("EndTable", MakeFunction(&ImGui::EndTable))
      .Function("TableNextRow", MakeFunction(&ImGui::TableNextRow))
      .Function("TableNextColumn", MakeFunction(&ImGui::TableNextColumn))
      .Function("TableSetColumnIndex", MakeFunction(&ImGui::TableSetColumnIndex))
      .Function("TableSetupColumn", MakeFunction(&ImGui::TableSetupColumn))
      .Function("TableSetupScrollFreeze", MakeFunction(&ImGui::TableSetupScrollFreeze))
      .Function("TableHeader", MakeFunction(&ImGui::TableHeader))
      .Function("TableHeadersRow", MakeFunction(&ImGui::TableHeadersRow))
      .Function("TableAngledHeadersRow", MakeFunction(&ImGui::TableAngledHeadersRow))
      .Function("TableGetSortSpecs", MakeFunction(&ImGui::TableGetSortSpecs))
      .Function("TableGetColumnCount", MakeFunction(&ImGui::TableGetColumnCount))
      .Function("TableGetColumnIndex", MakeFunction(&ImGui::TableGetColumnIndex))
      .Function("TableGetRowIndex", MakeFunction(&ImGui::TableGetRowIndex))
      .Function("TableGetColumnFlags", MakeFunction(&ImGui::TableGetColumnFlags))
      .Function("TableSetColumnEnabled", MakeFunction(&ImGui::TableSetColumnEnabled))
      .Function("TableSetBgColor", MakeFunction(&ImGui::TableSetBgColor))
      .Function("Columns", MakeFunction(&ImGui::Columns))
      .Function("NextColumn", MakeFunction(&ImGui::NextColumn))
      .Function("GetColumnIndex", MakeFunction(&ImGui::GetColumnIndex))
      .Function("GetColumnWidth", MakeFunction(&ImGui::GetColumnWidth))
      .Function("SetColumnWidth", MakeFunction(&ImGui::SetColumnWidth))
      .Function("GetColumnOffset", MakeFunction(&ImGui::GetColumnOffset))
      .Function("SetColumnOffset", MakeFunction(&ImGui::SetColumnOffset))
      .Function("GetColumnsCount", MakeFunction(&ImGui::GetColumnsCount))
      .Function("BeginTabBar", MakeFunction(&ImGui::BeginTabBar))
      .Function("EndTabBar", MakeFunction(&ImGui::EndTabBar))
      .Function("BeginTabItem", MakeFunction(&ImGui::BeginTabItem))
      .Function("EndTabItem", MakeFunction(&ImGui::EndTabItem))
      .Function("TabItemButton", MakeFunction(&ImGui::TabItemButton))
      .Function("SetTabItemClosed", MakeFunction(&ImGui::SetTabItemClosed))
      .Function("DockSpace", MakeFunction(&ImGui::DockSpace))
      .Function("DockSpaceOverViewport", MakeFunction(&ImGui::DockSpaceOverViewport))
      .Function("SetNextWindowDockID", MakeFunction(&ImGui::SetNextWindowDockID))
      .Function("SetNextWindowClass", MakeFunction(&ImGui::SetNextWindowClass))
      .Function("GetWindowDockID", MakeFunction(&ImGui::GetWindowDockID))
      .Function("IsWindowDocked", MakeFunction(&ImGui::IsWindowDocked))
      .Function("LogToTTY", MakeFunction(&ImGui::LogToTTY))
      .Function("LogToFile", MakeFunction(&ImGui::LogToFile))
      .Function("LogToClipboard", MakeFunction(&ImGui::LogToClipboard))
      .Function("LogFinish", MakeFunction(&ImGui::LogFinish))
      .Function("LogButtons", MakeFunction(&ImGui::LogButtons))
      .Function("LogText", SelectFunction(void(*)(char const*), &Wrapper::LogText))
      .Function("BeginDragDropSource", MakeFunction(&ImGui::BeginDragDropSource))
      .Function("EndDragDropSource", MakeFunction(&ImGui::EndDragDropSource))
      .Function("BeginDragDropTarget", MakeFunction(&ImGui::BeginDragDropTarget))
      .Function("AcceptDragDropPayload", MakeFunction(&ImGui::AcceptDragDropPayload))
      .Function("EndDragDropTarget", MakeFunction(&ImGui::EndDragDropTarget))
      .Function("GetDragDropPayload", MakeFunction(&ImGui::GetDragDropPayload))
      .Function("BeginDisabled", MakeFunction(&ImGui::BeginDisabled))
      .Function("EndDisabled", MakeFunction(&ImGui::EndDisabled))
      .Function("PushClipRect", MakeFunction(&ImGui::PushClipRect))
      .Function("PopClipRect", MakeFunction(&ImGui::PopClipRect))
      .Function("SetItemDefaultFocus", MakeFunction(&ImGui::SetItemDefaultFocus))
      .Function("SetKeyboardFocusHere", MakeFunction(&ImGui::SetKeyboardFocusHere))
      .Function("SetNextItemAllowOverlap", MakeFunction(&ImGui::SetNextItemAllowOverlap))
      .Function("IsItemHovered", MakeFunction(&ImGui::IsItemHovered))
      .Function("IsItemActive", MakeFunction(&ImGui::IsItemActive))
      .Function("IsItemFocused", MakeFunction(&ImGui::IsItemFocused))
      .Function("IsItemClicked", MakeFunction(&ImGui::IsItemClicked))
      .Function("IsItemVisible", MakeFunction(&ImGui::IsItemVisible))
      .Function("IsItemEdited", MakeFunction(&ImGui::IsItemEdited))
      .Function("IsItemActivated", MakeFunction(&ImGui::IsItemActivated))
      .Function("IsItemDeactivated", MakeFunction(&ImGui::IsItemDeactivated))
      .Function("IsItemDeactivatedAfterEdit", MakeFunction(&ImGui::IsItemDeactivatedAfterEdit))
      .Function("IsItemToggledOpen", MakeFunction(&ImGui::IsItemToggledOpen))
      .Function("IsAnyItemHovered", MakeFunction(&ImGui::IsAnyItemHovered))
      .Function("IsAnyItemActive", MakeFunction(&ImGui::IsAnyItemActive))
      .Function("IsAnyItemFocused", MakeFunction(&ImGui::IsAnyItemFocused))
      .Function("GetItemID", MakeFunction(&ImGui::GetItemID))
      .Function("GetItemRectMin", MakeFunction(&ImGui::GetItemRectMin))
      .Function("GetItemRectMax", MakeFunction(&ImGui::GetItemRectMax))
      .Function("GetItemRectSize", MakeFunction(&ImGui::GetItemRectSize))
      .Function("GetMainViewport", MakeFunction(&ImGui::GetMainViewport))
      .Function("GetBackgroundDrawList", SelectFunction(ImDrawList*(*)(), &ImGui::GetBackgroundDrawList))
      .Function("GetForegroundDrawList", SelectFunction(ImDrawList*(*)(), &ImGui::GetForegroundDrawList))
      .Function("GetBackgroundDrawList_1", SelectFunction(ImDrawList*(*)(ImGuiViewport*), &ImGui::GetBackgroundDrawList))
      .Function("GetForegroundDrawList_1", SelectFunction(ImDrawList*(*)(ImGuiViewport*), &ImGui::GetForegroundDrawList))
      .Function("IsRectVisible", SelectFunction(bool(*)(ImVec2 const&), &ImGui::IsRectVisible))
      .Function("IsRectVisible_1", SelectFunction(bool(*)(ImVec2 const&, ImVec2 const&), &ImGui::IsRectVisible))
      .Function("GetTime", MakeFunction(&ImGui::GetTime))
      .Function("GetFrameCount", MakeFunction(&ImGui::GetFrameCount))
      .Function("GetStyleColorName", MakeFunction(&ImGui::GetStyleColorName))
      .Function("SetStateStorage", MakeFunction(&ImGui::SetStateStorage))
      .Function("GetStateStorage", MakeFunction(&ImGui::GetStateStorage))
      .Function("ColorConvertU32ToFloat4", MakeFunction(&ImGui::ColorConvertU32ToFloat4))
      .Function("ColorConvertFloat4ToU32", MakeFunction(&ImGui::ColorConvertFloat4ToU32))
      .Function("GetKeyPressedAmount", MakeFunction(&ImGui::GetKeyPressedAmount))
      .Function("GetKeyName", MakeFunction(&ImGui::GetKeyName))
      .Function("SetNextFrameWantCaptureKeyboard", MakeFunction(&ImGui::SetNextFrameWantCaptureKeyboard))
      .Function("GetMouseClickedCount", MakeFunction(&ImGui::GetMouseClickedCount))
      .Function("IsMouseHoveringRect", MakeFunction(&ImGui::IsMouseHoveringRect))
      .Function("IsMousePosValid", MakeFunction(&ImGui::IsMousePosValid))
      .Function("IsAnyMouseDown", MakeFunction(&ImGui::IsAnyMouseDown))
      .Function("GetMousePos", MakeFunction(&ImGui::GetMousePos))
      .Function("GetMousePosOnOpeningCurrentPopup", MakeFunction(&ImGui::GetMousePosOnOpeningCurrentPopup))
      .Function("IsMouseDragging", MakeFunction(&ImGui::IsMouseDragging))
      .Function("GetMouseDragDelta", MakeFunction(&ImGui::GetMouseDragDelta))
      .Function("ResetMouseDragDelta", MakeFunction(&ImGui::ResetMouseDragDelta))
      .Function("GetMouseCursor", MakeFunction(&ImGui::GetMouseCursor))
      .Function("SetMouseCursor", MakeFunction(&ImGui::SetMouseCursor))
      .Function("SetNextFrameWantCaptureMouse", MakeFunction(&ImGui::SetNextFrameWantCaptureMouse))
      .Function("GetClipboardText", MakeFunction(&ImGui::GetClipboardText))
      .Function("SetClipboardText", MakeFunction(&ImGui::SetClipboardText))
      .Function("LoadIniSettingsFromDisk", MakeFunction(&ImGui::LoadIniSettingsFromDisk))
      .Function("LoadIniSettingsFromMemory", MakeFunction(&ImGui::LoadIniSettingsFromMemory))
      .Function("SaveIniSettingsToDisk", MakeFunction(&ImGui::SaveIniSettingsToDisk))
      .Function("DebugTextEncoding", MakeFunction(&ImGui::DebugTextEncoding))
      .Function("DebugFlashStyleColor", MakeFunction(&ImGui::DebugFlashStyleColor))
      .Function("DebugStartItemPicker", MakeFunction(&ImGui::DebugStartItemPicker))
      .Function("DebugCheckVersionAndDataLayout", MakeFunction(&ImGui::DebugCheckVersionAndDataLayout))
      .Function("UpdatePlatformWindows", MakeFunction(&ImGui::UpdatePlatformWindows))
      .Function("RenderPlatformWindowsDefault", MakeFunction(&ImGui::RenderPlatformWindowsDefault))
      .Function("DestroyPlatformWindows", MakeFunction(&ImGui::DestroyPlatformWindows))
      .Function("FindViewportByID", MakeFunction(&ImGui::FindViewportByID))
      .Function("FindViewportByPlatformHandle", MakeFunction(&ImGui::FindViewportByPlatformHandle))
      .Function("GetKeyIndex", MakeFunction(&ImGui::GetKeyIndex))
      .Function("Toggle", MakeFunction(&Wrapper::Toggle))
      .Function("SetNextWindowSizeConstraints", MakeFunction(&Wrapper::SetNextWindowSizeConstraints))
      .Function("Bg", MakeFunction(&Wrapper::Bg))
      .Function("Shadow", MakeFunction(&Wrapper::Shadow))
      .Function("GetPayloadData", MakeFunction(&Wrapper::GetPayloadData))
      .Function("SetDragDropPayload", MakeFunction(&Wrapper::SetDragDropPayload))
      .Function("SetScrollX", MakeFunction(&Wrapper::SetScrollX))
      .Function("SetScrollY", MakeFunction(&Wrapper::SetScrollY))
      .Function("IsKeyDown", MakeFunction(&Wrapper::IsKeyDown))
      .Function("IsKeyPressed", MakeFunction(&Wrapper::IsKeyPressed))
      .Function("IsKeyReleased", MakeFunction(&Wrapper::IsKeyReleased))
      .Function("IsMouseDown", MakeFunction(&Wrapper::IsMouseDown))
      .Function("IsMouseClicked", MakeFunction(&Wrapper::IsMouseClicked))
      .Function("IsMouseReleased", MakeFunction(&Wrapper::IsMouseReleased))
      .Function("IsMouseDoubleClicked", MakeFunction(&Wrapper::IsMouseDoubleClicked))
      .Function("CalcTextSize", MakeFunction(&Wrapper::CalcTextSize))
      .Function("ColorDummy", MakeFunction(&Wrapper::ColorDummy))
      .Function("GetWindowPosByName", MakeFunction(&Wrapper::GetWindowPosByName))
      .Function("GetWindowSizeByName", MakeFunction(&Wrapper::GetWindowSizeByName))
      .Function("FindWindowByName", MakeFunction(&Wrapper::FindWindowByName))
      .Function("SpinnerRainbowBalls", MakeFunction(&Wrapper::SpinnerRainbowBalls))
      .Function("GetCentralNodePos", MakeFunction(&Wrapper::GetCentralNodePos))
      .Function("GetCentralNodeSize", MakeFunction(&Wrapper::GetCentralNodeSize))
      .Function("InsertNotification", MakeFunction(&Wrapper::InsertNotification))
      .Function("RenderNotifications", MakeFunction(&Wrapper::RenderNotifications))
      .Function("SetNotifyViewportSize", MakeFunction(&Wrapper::SetNotifyViewportSize))
      .Function("SetNotifyViewportPos", MakeFunction(&Wrapper::SetNotifyViewportPos))
      .Function("DockBuilderDockWindow", MakeFunction(&Wrapper::DockBuilderDockWindow))
      .Function("DockBuilderSplitNode", MakeFunction(&Wrapper::DockBuilderSplitNode))
      .Function("SetColor", MakeFunction(&Wrapper::SetColor))
      .Function("ImageRounded", MakeFunction(&Wrapper::ImageRounded))
        .Function("InputText",
                  MakeFunction(&Wrapper::InputText, 0, nullptr))
        .Function("InputTextMultiline",
                  MakeFunction(&Wrapper::InputTextMultiline, ImVec2(0, 0),
                               0, nullptr))  // callback
        .Function("InputTextWithHint",
                  MakeFunction(&Wrapper::InputTextWithHint, 0,
                               nullptr))  // callback
        .Function("Image",
                  CombineOverloads(
                      MakeOverload(void (*)(FImGuiTextureHandle, const ImVec2&,
                                            const ImVec2&, const ImVec2&,
                                            const ImVec4&, const ImVec4&),
                                   &Wrapper::Image),
                      MakeOverload(void (*)(FImGuiTextureHandle, const ImVec2&,
                                            const ImVec4&),
                                   &Wrapper::Image),
                      MakeOverload(void (*)(FImGuiTextureHandle, const ImVec2&),
                                   &Wrapper::Image)))
        .Function("RegisterTexture",
                  MakeFunction(&Wrapper::RegisterTexture, false))
        .Function("ReleaseTexture", MakeFunction(&Wrapper::ReleaseTexture))
        .Function("ClearTextures", MakeFunction(&Wrapper::ClearTextures))
        .Function("FindTextureHandle",
                  MakeFunction(&Wrapper::FindTextureHandle))
        .Function("DockBuilderRemoveNodeDockedWindows", MakeFunction(&ImGui::DockBuilderRemoveNodeDockedWindows))
        .Function("DockBuilderRemoveNodeChildNodes", MakeFunction(&ImGui::DockBuilderRemoveNodeChildNodes))
        .Function("DockBuilderFinish", MakeFunction(&ImGui::DockBuilderFinish))
        .Function("Combo", SelectFunction(bool (*)(const char*, int*, const char*, int), &ImGui::Combo))
        .Function("PlotLines", SelectFunction(void (*)(const char*, const float*, int, int, const char*, float, float, ImVec2, int), &ImGui::PlotLines))
        .Function("PlotHistogram", SelectFunction(void (*)(const char*, const float*, int, int, const char*, float, float, ImVec2, int), &ImGui::PlotLines))
        .Register();
  }
};

AutoRegisterForDearImGui _AutoRegisterForImGui__;
